#routes.yaml

limur_map_get_geo_data_from_nominatim:
  path:     /map/nominatim/geo
  methods: POST
  controller: limur_map_controller_nominatim::geoAction

limur_map_get_geo_data_from_sputnik:
  path:     /map/sputnik/geo
  methods: POST
  controller: limur_map_controller_sputnik::geoAction
