#services.yml

services:

  Limur\Map\Service\Nominatim: ~

  Limur\Map\Service\Sputnik: ~

  Limur\Map\Service\MapInterface $map: '@Limur\Map\Service\Nominatim'

  Limur\Map\Service\MapInterface: '@Limur\Map\Service\Sputnik'

  limur_map_controller_nominatim:
    public: true
    class: Limur\Map\Controller\MapController
    autowire: true
    arguments:
      $map: '@Limur\Map\Service\Nominatim'

  limur_map_controller_sputnik:
    public: true
    class: Limur\Map\Controller\MapController
    autowire: true
    arguments:
      $map: '@Limur\Map\Service\Sputnik'
